- name: Return all available z/OS facts.
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:

  - name: Return all avaialble z/OS facts.

    ibm.ibm_zos_core.zos_gather_facts:
      gather_subset: sys
      register: zos_facts 

  - name: Print return info from previous task
    ansible.builtin.debug:
      var: zos_facts 
      
        