- name: Return all Started Tasks.
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:

  name: Display all started tasks.
  zos_started_task:
    state: "displayed"
    job_name: "all"
       
  register: stcs


 name: Print return info from previous task
    ansible.builtin.debug:
      var: stcs 

      
 #  - name: Print return info from previous task
 #   ansible.builtin.debug:
 #     var: zos_facts 

 # - name: Print return info from previous task
 #   ansible.builtin.debug:
 #     var: zos_facts     
        