- name: Return all Started Tasks.
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:

  - name: Display all started tasks.
      ibm.ibm_zos_core.zos_job_query:
      register: active_jobs
    - name: Keep only started tasks
      set_fact:
        stcs: >-
        {{
          active_jobs.jobs
        | selectattr('job_class', 'defined')
        | selectattr('job_class', 'equalto', 'STC')
        | list
        }}
    - name: Display Results
      ansible.builtin.debug:
       msg: "{{ started_tasks | map(attribute='job_name') | list }}" 




# name: Display all started tasks.
#  ibm.ibm_zos_core.zos_started_task:
#    state: "displayed"
#    job_name: "all"
       
#  register: stcs


# name: Print return info from previous task
#    ansible.builtin.debug:
#      var: stcs 

      
 #  - name: Print return info from previous task
 #   ansible.builtin.debug:
 #     var: zos_facts 

 # - name: Print return info from previous task
 #   ansible.builtin.debug:
 #     var: zos_facts     
        